# Routes du CoachingBundle
sadio_coaching:
    resource: "@SadioCoachingBundle/Resources/config/routing.yml"
    prefix:   /services/

# Routes du AuthBundle
sadio_auth:
    resource: "@SadioAuthBundle/Resources/config/routing.yml"
    prefix:   /

# Routes du CoreBundle
core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: "|en|fr"
