# Routes du AuthBundle
sadio_auth:
    resource: "@SadioAuthBundle/Resources/config/routing.yml"
    prefix:   /h

# Routes du CoreBundle
core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /
