<?php

namespace CoreBundle\Repository;

/**
 * EducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationRepository extends \Doctrine\ORM\EntityRepository
{
    // On recupère les résultats au format Array pour optimiser le temps de traitement. 
    // On peut se le permettre vu que nous n'aurons pas besoin de faire $entité->setAttr() une fois les entités recupérés de la BDD
    public function findAllArray() 
    {
        return $this->createQueryBuilder('ed')
                    ->orderBy('ed.id', 'DESC')
                    ->getQuery()->getArrayResult();
    }
}
