<?php

namespace CoreBundle\Repository;

/**
 * ProjectRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    // Permet de récupérer les Projects avec leurs Images correspondantes => quand on fait project.getImage dans TWIG, 
    // Pas de requetes SQL supplémentaire déclenchée
    public function findAllWithImage() 
    {
        // "p" represente l'alias de Project et "i" celui de Image
        $qb = $this->createQueryBuilder('p');

        $qb->innerJoin('p.image', 'i')
           ->addSelect('i')
           ->orderBy('p.id', 'DESC');
        
        // On recupère les résultats au format Array pour optimiser le temps de traitement. 
        // On peut se le permettre vu que nous n'aurons pas besoin de faire $project->setAttr() une fois les projects recupérés de la BDD
        return $qb->getQuery()->getArrayResult();
    }
}
